version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "8000:8000"
      - "8100:8100"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log



